Add eslint-plugin-es5
logux/eslint-config pull request #2
Opened 2017-01-03 15:32 UTC by nkt

2017-01-03 16:28 UTC, ai commented
If you have mode non-ES6 rules you can enable more rules :)

2017-01-03 16:33 UTC, ai requested changes

2017-01-03 16:33 UTC, ai commented on index.js
> +    'es5/no-arrow-functions': 'error'
Feel free to enable more rules, if you have them.

2017-01-03 16:33 UTC, ai commented on package.json
> +    "eslint-plugin-es5": "^0.2.0",
Why you use `0.2` version if you already released `0.3`?

2017-01-04 00:40 UTC, nkt commented
@ai plugin have been unfinished when I sent this PR. But now it's good enough for production usage.
PR updated, please review it.

2017-01-04 06:22 UTC, ai approved these changes

2017-01-04 06:22 UTC, merged

2017-01-04 06:26 UTC, ai commented
@nkt thanks for your work. I will promote it tomorrow or after-tomorrow. Anyway internet is not active right now :).